# Generated by Django 5.0 on 2024-01-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='breed',
        ),
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
