# Generated by Django 5.0 on 2024-02-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_namae',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_namae',
            new_name='last_name',
        ),
    ]
